.TH bf2int 3 "JULY 10, 2016" "bitfield 0.6.0" "Bitfield manipulation library"
.SH NAME
bf2int, bf2int_ip, int2bf, int2bf_ip \- convert a bit array to an array of integers, and vice-versa.
.SH SYNOPSIS
.nf
.B "#include <bitfield.h>
.sp
.BI "unsigned int *bf2int(const struct bitfield *"input ");
.BI "void bf2int_ip(const struct bitfield *"input ", unsigned int *"output ");
.BI "struct bitfield *int2bf(const unsigned int *"input ", int "size ");
.BI "void int2bf_ip(const unsigned int *"input ", struct bitfield *"output ");
.fi
.SH DESCRIPTION
A bitfield is represented by a "struct bitfield". It has two elements: an array of unsigned long integers \fIfield\fR and an integer \fIsize\fR.
.sp
The \fBbf2int()\fR function takes a pointer to a bitfield \fIinput\fR and returns an array of integers containing the bits.
.sp
The \fBbf2int_ip()\fR function takes a pointer to bitfield \fIinput\fR and an array of integers \fIoutput\fR, and copies the bits from \fIinput\fR to \fIoutput\fR "in-place".
.sp
The \fBint2bf()\fR function takes a pointer to an array of unsigned integers \fIinput\fR containing the bit array and an integer \fIsize\fR, copies the bit array into a bitfield structure of given \fRsize\fR, and returns a pointer to the newly created structure.
.sp
The \fBint2bf_ip()\fR function takes an array of integers \fIinput\fR and a pointer to a properly initialized bitfield \fIoutput\fR, and copies the bits from \fIinput\fR to \fIoutput\fR "in place".
.sp
.SH "SEE ALSO"
For the full list of bitfield functions and their descriptions, see manual page for
.BR bitfield (3).
.SH AUTHOR
Vitalie CIUBOTARU

