.TH bf2long 3 "JULY 10, 2016" "bitfield 0.6.0" "Bitfield manipulation library"
.SH NAME
bf2long, bf2long_ip, long2bf, long2bf_ip \- convert a bit array to an array of long integers, and vice-versa.
.SH SYNOPSIS
.nf
.B "#include <bitfield.h>
.sp
.BI "unsigned long *bf2long(const struct bitfield *"input ");
.BI "void long2bf_ip(const unsigned long *"input ", struct bitfield *"output ");
.BI "struct bitfield *long2bf(const unsigned long *"input ", int "size ");
.BI "void bf2long_ip(const struct bitfield *"input ", unsigned long *"output ");
.fi
.SH DESCRIPTION
A bitfield is represented by a "struct bitfield". It has two elements: an array of unsigned long integers \fIfield\fR and an integer \fIsize\fR.
.sp
The \fBbf2long()\fR function takes a pointer to a bitfield \fIinput\fR and returns an array of long integers containing the bits.
.sp
The \fBbf2long_ip()\fR function takes a pointer to bitfield \fIinput\fR and an array of long integers \fIoutput\fR, and copies the bits from \fIinput\fR to \fIoutput\fR "in-place".
.sp
The \fBlong2bf()\fR function takes a pointer to an array of unsigned long integers \fIinput\fR containing the bit array and an integer \fIsize\fR, copies the bit array into a bitfield structure of given \fRsize\fR, and returns a pointer to the newly created structure.
.sp
The \fBlong2bf_ip()\fR function takes an array of long integers \fIinput\fR and a pointer to a properly initialized bitfield \fIoutput\fR, and copies the bits from \fIinput\fR to \fIoutput\fR "in place".
.sp
.SH "SEE ALSO"
For the full list of bitfield functions and their descriptions, see manual page for
.BR bitfield (3).
.SH AUTHOR
Vitalie CIUBOTARU

