.TH bf2short 3 "SEPTEMBER 1, 2016" "bitfield 0.6.0" "Bitfield manipulation library"
.SH NAME
bf2short, bf2short_ip, short2bf, short2bf_ip \- convert a bit array to an array of short integers, and vice-versa.
.SH SYNOPSIS
.nf
.B "#include <bitfield.h>
.sp
.BI "unsigned short *bf2short(const struct bitfield *"input ");
.BI "void short2bf_ip(const unsigned short *"input ", struct bitfield *"output ");
.BI "struct bitfield *short2bf(const unsigned short *"input ", int "size ");
.BI "void bf2short_ip(const struct bitfield *"input ", unsigned short *"output ");
.fi
.SH DESCRIPTION
A bitfield is represented by a "struct bitfield". It has two elements: an array of unsigned long integers \fIfield\fR and an integer \fIsize\fR.
.sp
The \fBbf2short()\fR function takes a pointer to a bitfield \fIinput\fR and returns an array of short integers containing the bits.
.sp
The \fBbf2short_ip()\fR function takes a pointer to bitfield \fIinput\fR and an array of short integers \fIoutput\fR, and copies the bits from \fIinput\fR to \fIoutput\fR "in-place".
.sp
The \fBshort2bf()\fR function takes a pointer to an array of unsigned short integers \fIinput\fR containing the bit array and an integer \fIsize\fR, copies the bit array into a bitfield structure of given \fRsize\fR, and returns a pointer to the newly created structure.
.sp
The \fBshort2bf_ip()\fR function takes an array of short integers \fIinput\fR and a pointer to a properly initialized bitfield \fIoutput\fR, and copies the bits from \fIinput\fR to \fIoutput\fR "in place".
.sp
.SH "SEE ALSO"
For the full list of bitfield functions and their descriptions, see manual page for
.BR bitfield (3).
.SH AUTHOR
Vitalie CIUBOTARU

