.TH bfcat 3 "OCTOBER 1, 2015" "bitfield 0.1.2" "Bitfield manipulation library"
.SH NAME
bfcat \- concatenate two bitfields into one.
.SH SYNOPSIS
.nf
.B "#include <bitfield.h>
.sp
.BI "struct bitfield *bfcat(const struct bitfield *"input1 ", const struct bitfield *"input2 ");
.fi
.SH DESCRIPTION
A bitfield is represented by a "struct bitfield". It has two elements: an array of unsigned long integers \fIfield\fR and an integer \fIsize\fR.
.sp
The \fBbfcat()\fR function takes pointers to two bitfields, \fIinput1\fR and \fIinput2\fR, and creates a new bitfield that contains all bits from the first and from the second. The function returns a pointer to the new bitfield.
.sp
.SH "SEE ALSO"
For the full list of bitfield functions and their descriptions, see manual page for
.BR bitfield (3).
.SH AUTHOR
Vitalie CIUBOTARU

