.TH bfcpy 3 "OCTOBER 15, 2015" "bitfield 0.1.2" "Bitfield manipulation library"
.SH NAME
bfcpy \- copies the contents of a bitfield into another pre-existing bitfield.
.SH SYNOPSIS
.nf
.B "#include <bitfield.h>
.sp
.BI "int bfcpy(const struct bitfield *"src ", struct bitfield *"dest ");
.fi
.SH DESCRIPTION
A bitfield is represented by a "struct bitfield". It has two elements: an array of unsigned long integers \fIfield\fR and an integer \fIsize\fR.
.sp
The \fBbfcpy()\fR function takes pointers to bitfields \fIsrc\fR and \fIdest\fR, and copies the bits from \fIsrc\fR to \fIdest\fR bit. The function returns 0 on success and 1 otherwise.
.sp
.SH "SEE ALSO"
For the full list of bitfield functions and their descriptions, see manual page for
.BR bitfield (3).
.SH AUTHOR
Vitalie CIUBOTARU

