.TH bfpopcount 3 "JUNE 10, 2017" "bitfield 0.6.4" "Bitfield manipulation library"
.SH NAME
bfpopcount \- counts the set bits in a bit array.
.SH SYNOPSIS
.nf
.B "#include <bitfield.h>
.sp
.BI "unsigned int bfpopcount(const struct bitfield *"instance ");
.fi
.SH DESCRIPTION
A bitfield is represented by a "struct bitfield". It has two elements: an array of unsigned long integers \fIfield\fR and an unsigned integer \fIsize\fR.
.sp
The \fBbfpopcount()\fR function is an implementation of population count (known as the Hamming weight) of a bitfield. It takes pointers to bitfield \fIinstance\fR and returns the number of set bits in it.
.sp
.SH "SEE ALSO"
For the full list of bitfield functions and their descriptions, see manual page for
.BR bitfield (3).
.SH AUTHOR
Vitalie CIUBOTARU

