.TH bfsize 3 "JUNE 10, 2017" "bitfield 0.6.4" "Bitfield manipulation library"
.SH NAME
bfsize \- obtain the number of bits of a bitfield.
.SH SYNOPSIS
.nf
.B "#include <bitfield.h>
.sp
.BI "unsigned int bfsize(const struct bitfield *"instance ");
.fi
.SH DESCRIPTION
A bitfield is represented by a "struct bitfield". It has two elements: an array of unsigned long integers \fIfield\fR and an unsigned integer \fIsize\fR.
.sp
The \fBbfsize()\fR function takes pointers to a bitfield \fIinstance\fR and returns its \fIsize\fR (the number of bits).
.sp
.SH "SEE ALSO"
For the full list of bitfield functions and their descriptions, see manual page for
.BR bitfield (3).
.SH AUTHOR
Vitalie CIUBOTARU

