.TH bfsub 3 "NOVEMBER 1, 2015" "bitfield 0.2.0" "Bitfield manipulation library"
.SH NAME
bfsub \- extract a sub-bitfield from a bitfield.
.SH SYNOPSIS
.nf
.B "#include <bitfield.h>
.sp
.BI "struct bitfield *bfsub(const struct bitfield *"input ", const unsigned int "start ", const unsigned int "end ");
.fi
.SH DESCRIPTION
A bitfield is represented by a "struct bitfield". It has two elements: an array of unsigned long integers \fIfield\fR and an integer \fIsize\fR.
.sp
The \fBbfsub()\fR function takes a pointer to bitfield \fIinput\fR, the number of the \fIstart\fR bit and \fIend\fR bit, and creates a new bitfield that contains bits between \fIstart\fR (included) bit and \fIend\fR(not included) bit from the \fIinput\fR bitfield. The function returns a pointer to the new bitfield.
.sp
.SH "SEE ALSO"
For the full list of bitfield functions and their descriptions, see manual page for
.BR bitfield (3).
.SH AUTHOR
Vitalie CIUBOTARU

