.TH bfzero 3 "SEPTEMBER 20, 2015" "bitfield 0.1.1" "Bitfield manipulation library"
.SH NAME
bfzero, bfone \- fills a bitfield with values.
.SH SYNOPSIS
.nf
.B "#include <bitfield.h>
.sp
.BI "void bfzero(struct bitfield *"instance ");
.BI "void bfone(struct bitfield *"instance ");
.fi
.SH DESCRIPTION
A bitfield is represented by a "struct bitfield". It has two elements: an array of unsigned long integers \fIfield\fR and an integer \fIsize\fR.
.sp
The \fBbfzero()\fR function takes a pointer to bitfield \fIinstance\fR, and sets all its bits to zero.
.sp
The \fBbfone()\fR function takes a pointer to bitfield \fIinstance\fR, and sets all its bits to one.
.sp
.SH "SEE ALSO"
.BR bfnew (3),
.BR bfdel (3),
.BR bfcmp (3),
.BR bfprint (3),
.BR char2bf (3),
.BR bf2char (3),
.BR bfcat (3),
.BR bfshift (3)
.SH COLOPHON
.SH AUTHOR
Vitalie CIUBOTARU

