.TH long2bf 3 "MARCH 20, 2016" "bitfield 0.4" "Bitfield manipulation library"
.SH NAME
long2bf \- converts an array of long integers into a bitfield structure.
.SH SYNOPSIS
.nf
.B "#include <bitfield.h>
.sp
.BI "struct bitfield *long2bf(unsigned long *"input ", int "size ");
.fi
.SH DESCRIPTION
A bitfield is represented by a "struct bitfield". It has two elements: an array of unsigned long integers \fIfield\fR and an integer \fIsize\fR.
.sp
The \fBlong2bf()\fR function takes a pointer to an array of unsigned long integers \fIinput\fR containing the bit array and an integer \fIsize\fR, copies the bit array into a bitfield structure of given \fRsize\fR, and returns a pointer to the newly created structure.
.sp
.SH "SEE ALSO"
For the full list of bitfield functions and their descriptions, see manual page for
.BR bitfield (3).
.SH AUTHOR
Vitalie CIUBOTARU

